[package]
name = "goole-cloud-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
google-cloud-gax = { version = "0.5.0", path = "../foundation/gax" }
google-cloud-googleapis= {  version = "0.4.0", path = "../googleapis", features=["storage"]}
rsa = "0.6"
thiserror = "1.0"
chrono = "0.4"
base64 = "0.13"
regex = "1.5"
urlencoding = "2.1"
sha2 = "0.10"
base16ct = "0.1"
ring = "0.17.0-alpha.11"
tokio = "1.17"
async-stream = "0.3"
once_cell = "1.10"
hex = "0.4.3"
url = "2.2.2"

[dev-dependencies]
google-cloud-auth = { version = "0.2.0", path = "../foundation/auth" }
serial_test = "0.5.1"