[package]
name = "goole-cloud-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
google-cloud-gax = { version = "0.5.0", path = "../foundation/gax" }
google-cloud-googleapis= {  version = "0.4.0", path = "../googleapis", features=["storage"]}
rsa = "0.6"
thiserror = "1.0"
chrono = "0.4"
base64 = "0.13"
regex = "1.5"
urlencoding = "2.1"
sha2 = "0.10"
base16ct = "0.1"